### ISSUE TITLE
Outlining streets but won't generate the route.

### ISSUE THREAD

**Issue by Treysf** [matejker/everystreet#10]
Hello! I'm new to github and joined to cite issues I've been having on everystreetchallenge.com. I have been using the software for a few weeks now and it has helped me create routes to run every street in my city (Reno, Nevada). I coming across this problem where I try to outline an area in a several neighborhoods and then click on generate, it pops up an error message that says "undefined" and "route can't be generated". It then brings me back to the home back, erasing my selection. It does this constantly with the same areas and nothing seems to fix it (refreshing, restarting PC). I would like to know if there is a way to fix this or someway to work around it. Do it have to run it locally? Anyways, I've attached a photo of a broken selection and of the error message that I receive.
 [
![IMG_3785](https://user-images.githubusercontent.com/89662323/131180444-0eaaa565-e916-4fb6-aa04-091d1e0c7323.JPG)
![Screenshot (2)](https://user-images.githubusercontent.com/89662323/131180466-1b5d515a-2bc9-4f26-b5ad-d36f21c1de3e.png)
](url)

**Comment by matejker** [comment]
Hi!

Yeah, I am getting the same error. It is hard to say what is the issue, but usually it is because the OSM is broken in that area / `OSMnx` package can't process it. I tried to generate [smaller area](http://www.everystreetchallenge.com/route/b1195a50-f88f-4abf-b737-33dbe4337fed) and it worked... 

My advice would be to try smaller areas and maybe some of them will work...

In general it is hard to make sure that all areas are working well. The OSM is an _open source_ map provider and community developed, so problems like this will aways occur :/

**Comment by matejker** [comment]
Hi @Treysf, 

the web service should be back, although, for larger maps it can time out, therefore, highly recommend to install it locally :)
