### ISSUE TITLE
hierholzer algorithm not found

### ISSUE THREAD

**Issue by Aswath98** [matejker/everystreet#9]
I am trying to implement the problem using python. When I try running the code, hierholzer is not found in network algorithms. Can you give me an solution ?

**Comment by Aswath98** [comment]
Yes, I am using networkx==2.4 package and pip to install.
But in the networkx package, I couldn't find the algorithm

**Comment by matejker** [comment]
I see, the issue is the Hierholzer algorithm isn't in `networkx` package, but it is in [matejker/network](https://github.com/matejker/network), see it in [network/algorithms/eulerian.py#L33 ](https://github.com/matejker/network/blob/master/network/algorithms/eulerian.py#L33).

The jupyter notebook is importing it `from network.algorithms import hierholzer`.

**Comment by Aswath98** [comment]
Oh! got it. Thanks. How can I get the results from gpx file ?

**Comment by Aswath98** [comment]
Thanks a lot. I am using this for my college project. Could you please say
how can I use this to obtain the results in the form of a gpx file?
Thanks in advance

**Comment by matejker** [comment]
Sure, I think this could help you: https://github.com/matejker/everystreet/issues/6#issuecomment-774651380

What kind of collage project do you do? if I may ask :)

**Comment by Aswath98** [comment]
Thanks a lot. This is so helpful.

This is my university project.
Objective - For a given area, travel through all the roads via car.
Input - neighborhood area
Output - gpx trace covering all roads
Initially I tried implementing using Chinese postman problem and then
inputting the waypoints in routing engines. It couldn't handle one ways. It
gave illegal u turns etc., Then I found this very interesting and usefull
one.
